language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t danems11/docker-react .

script:
  - docker run -e CI=true danems11/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-577613759552"
  bucket_path: "docker"

  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  #Docker-env.eba-mfz9xj2k.us-east-1.elasticbeanstalk.com